[tool.black]
line-length = 100
target-version = ['py38']
exclude = '''
/(
  dist
  | libs
  | venv
)/
'''

[tool.isort]
line_length = 100
force_single_line = true
skip = ['dist', 'venv', 'libs', 'layer']